/**
 * smartLoop.ts
 * 智能循环：重复祖先分析、候选高亮
 */

import type { RepeatingCandidate } from '@shared/types/message'
import { MSG } from '@shared/types/message'
import { getCssSelector, serializeElement } from './domScanner'

// ─── 智能循环候选高亮状态 ─────────────────────────────────────────────────────
const loopHighlightEls: HTMLElement[] = []

// ─── 辅助函数 ─────────────────────────────────────────────────────────────────

/** class 名看起来像自动生成（含大量数字/过长），则视为不稳定 */
function isAutoGeneratedClass(cls: string): boolean {
  if (/^[a-f0-9]{5,}$/i.test(cls)) return true  // 纯 hex hash
  if (/[0-9]{3,}/.test(cls)) return true          // 含 3+ 位连续数字
  if (cls.length > 20) return true                 // 过长
  return false
}

/** 构建列表项的匹配片段（tag + 稳定 class，不含位置伪类） */
function buildItemSegment(el: Element): string {
  const tag           = el.tagName.toLowerCase()
  const stableClasses = [...el.classList].filter(c => !isAutoGeneratedClass(c)).slice(0, 2)
  if (stableClasses.length === 0) return tag
  return tag + stableClasses.map(c => `.${CSS.escape(c)}`).join('')
}

/** 构建相对路径中某层元素的片段（尽量用 class，否则 nth-child 兜底） */
function buildRelativeSegment(el: Element): string {
  const tag      = el.tagName.toLowerCase()
  const parent   = el.parentElement
  if (!parent) return tag
  const siblings = Array.from(parent.children)

  // 同 tag 只有一个 → tag 即可唯一定位
  if (siblings.filter(s => s.tagName === el.tagName).length === 1) return tag

  // 尝试 tag + 稳定 class 组合
  const stableClasses = [...el.classList].filter(c => !isAutoGeneratedClass(c)).slice(0, 2)
  if (stableClasses.length > 0) {
    const clsPart    = stableClasses.map(c => `.${CSS.escape(c)}`).join('')
    const matchCount = siblings.filter(s => {
      if (s.tagName !== el.tagName) return false
      const sCls = [...s.classList].filter(c => !isAutoGeneratedClass(c)).slice(0, 2)
      return sCls.join(',') === stableClasses.join(',')
    }).length
    if (matchCount === 1) return `${tag}${clsPart}`
  }

  // 兜底：nth-child
  return `${tag}:nth-child(${siblings.indexOf(el) + 1})`
}

/** 将 pathUp（从 item 子节点到 pickedEl 的元素列表）拼成相对选择器 */
function buildRelativePath(pathUp: Element[]): string {
  return pathUp.map(el => buildRelativeSegment(el)).join(' > ')
}

/** 根据 tagName / role / class 推断人类可读的中文标签 */
function inferCandidateLabel(el: Element): string {
  const tag = el.tagName.toLowerCase()
  const tagLabels: Record<string, string> = {
    tr: '表格行', li: '列表项', td: '表格列', th: '表头列',
    option: '下拉选项', dt: '定义项', dd: '定义说明',
  }
  if (tagLabels[tag]) return tagLabels[tag]

  const role = el.getAttribute('role') ?? ''
  const roleLabels: Record<string, string> = {
    row: '表格行', listitem: '列表项', option: '选项',
    treeitem: '树节点', tab: '标签页', menuitem: '菜单项',
  }
  if (roleLabels[role]) return roleLabels[role]

  const cls = [...el.classList].join(' ').toLowerCase()
  if (cls.includes('card'))    return '卡片'
  if (cls.includes('item'))    return '列表项'
  if (cls.includes('row'))     return '行'
  if (cls.includes('result'))  return '结果项'
  if (cls.includes('entry'))   return '条目'
  if (cls.includes('product')) return '商品'
  return `${tag} 元素组`
}

/**
 * 从拾取的元素往上爬 DOM，找出所有「同级有重复兄弟」的祖先层作为候选列表项。
 */
function analyzeRepeatingAncestors(pickedEl: Element): RepeatingCandidate[] {
  const candidates: RepeatingCandidate[] = []
  const MAX_DEPTH = 8
  let current: Element | null = pickedEl
  const pathUp: Element[] = []
  let depth = 0

  while (
    current &&
    current !== document.body &&
    current !== document.documentElement &&
    depth <= MAX_DEPTH
  ) {
    const parent = current.parentElement
    if (parent && parent !== document.documentElement) {
      const sameSiblings = Array.from(parent.children).filter(s => s.tagName === current!.tagName)
      if (sameSiblings.length >= 2) {
        const parentSel  = getCssSelector(parent)
        const itemSel    = `${parentSel} > ${buildItemSegment(current)}`
        let count = 0
        try { count = document.querySelectorAll(itemSel).length } catch { /* 无效选择器，跳过 */ }
        if (count >= 2) {
          candidates.push({
            itemSelector:     itemSel,
            relativeSelector: buildRelativePath(pathUp),
            count,
            tagName:          current.tagName,
            inferredLabel:    inferCandidateLabel(current),
            depth,
          })
        }
      }
    }
    pathUp.unshift(current)
    current = current.parentElement
    depth++
  }
  return candidates
}

// ─── 对外接口 ─────────────────────────────────────────────────────────────────

export function handleSmartLoopFromSelector(cssSelector: string): void {
  let el: Element | null
  try { el = document.querySelector(cssSelector) } catch { el = null }
  if (!el) {
    chrome.runtime.sendMessage({ type: MSG.SMART_LOOP_ANALYZED, element: null, candidates: [] }).catch(() => {})
    return
  }
  const serialized = serializeElement(el, null)
  const candidates = analyzeRepeatingAncestors(el)
  if (serialized) {
    chrome.runtime.sendMessage({ type: MSG.SMART_LOOP_ANALYZED, element: serialized, candidates }).catch(() => {})
  }
}

export function handleHighlightCandidates(selector: string): void {
  clearLoopHighlights()
  let items: NodeListOf<Element>
  try { items = document.querySelectorAll(selector) } catch { return }
  items.forEach(item => {
    const r = item.getBoundingClientRect()
    if (r.width === 0 && r.height === 0) return
    const hl = document.createElement('div')
    Object.assign(hl.style, {
      position: 'fixed', pointerEvents: 'none', zIndex: '2147483644',
      left: `${r.left}px`, top: `${r.top}px`,
      width: `${r.width}px`, height: `${r.height}px`,
      background: 'rgba(250,179,135,.2)',
      border: '2px solid #fab387',
      borderRadius: '2px',
    })
    document.body.appendChild(hl)
    loopHighlightEls.push(hl)
  })
}

export function clearLoopHighlights(): void {
  loopHighlightEls.forEach(el => el.remove())
  loopHighlightEls.length = 0
}
